# category.form.edit.yaml
title: 教程管理
model: BooksModel
# AJAX添加与编辑的提交地址
ajax_add_url: /admins/books/add
ajax_edit_url: /admins/books/edit

show_fields:

edit_fields:
    parent_id: 
        title: ID
        element: input-text
        type: text
        id: id
        name: id
        className: form-control
        placeholder: '教程ID'
    platform:
        title: 平台
        element: input-text
        type: text
        id: platform
        name: platform
        className: form-control
        placeholder: '平台'
    category:
        title: 分类
        element: input-text
        type: text
        id: category
        name: category
        className: form-control
        placeholder: 'category'
    book_name:
        title: 中文名
        element: input-text
        type: text
        id: book_name
        name: book_name
        className: form-control
        placeholder: '中文名'
    book_name_en:
        title: 英文名
        element: input-text
        type: text
        id: book_name_en
        name: book_name_en
        className: form-control
        placeholder: '英文名'
    book_description:
        title: 描述
        element: textarea
        type: textarea
        id: book_description
        name: book_description
        className: form-control
        placeholder: '描述'
    notes:
        title: 备注
        element: textarea
        type: textarea
        id: notes
        name: notes
        className: form-control
        placeholder: '备注'
edit_buttons:
    add_button: '保存修改'
    edit_button: '保存修改'
